services:
  - type: web
    name: fuetime
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip
      python -m pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:10000 --worker-class eventlet --workers 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONFAULTHANDLER
        value: 1
      - key: PYTHONHASHSEED
        value: random
