services:
  - type: web
    name: fuetime
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn --worker-class eventlet --workers 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONFAULTHANDLER
        value: 1
      - key: PYTHONHASHSEED
        value: random
