"""Initial migration

Revision ID: 3336c89adb02
Revises: 
Create Date: 2025-06-21 15:55:43.513677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3336c89adb02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_interaction')
    op.drop_table('transaction')
    op.drop_table('contact_request')
    op.drop_table('help_request')
    op.drop_table('saved_workers')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_experience', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('work_experience')

    op.create_table('saved_workers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('worker_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'worker_id', name=op.f('unique_saved_worker'))
    )
    op.create_table('help_request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ticket_id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('solution', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    op.create_table('contact_request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('requester_id', sa.INTEGER(), nullable=False),
    sa.Column('requested_id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['requested_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_interaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('viewer_id', sa.INTEGER(), nullable=False),
    sa.Column('viewed_id', sa.INTEGER(), nullable=False),
    sa.Column('interaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['viewed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['viewer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
